### ISSUE TITLE
[BUG] "s6-rc-init: fatal: unable to supervise service directories in /run/s6-rc/servicedirs: Broken pipe" when starting container

### ISSUE THREAD

**Issue by scottdrmyers** [linuxserver/docker-tautulli#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had watchtower update the container automatically and saw that it was not running. I then re-deployed as a stack and still get the same error. This has been working for months with no changes except automatically container upgrades.

I have 15 other containers running without issues with no conflicting ports.

### Expected Behavior

Container should start normally.

### Steps To Reproduce

Nothing special here. Just simply try to deploy the container. As a test, I deployed on a second docker host, same results.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: https://docs.docker.com/engine/install/ubuntu/ - Using apt repo. Stays current with sudo apt update && sudo apt upgrade commands.
```

### CPU architecture

x86-64

### Docker creation

```bash
`version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax
    volumes:
      - /home/minipc/tautulli/config:/config
    ports:
      - 48181:8181
    restart: always`
```

### Container logs

```bash
`2024-01-12T03:03:16.755837697Z s6-rc-init: fatal: unable to supervise service directories in /run/s6-rc/servicedirs: Broken pipe`

Nothing else in the log unless there is a specific place to look for more info.
```

**Comment by scottdrmyers** [comment]
Note: I deployed the following as a test:

```
version: '3'
services:
  tautulli:
    image: **ghcr.io/tautulli/tautulli:latest**
    container_name: tautulli
    restart: always
    volumes:
      - /home/minipc/tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax
    ports:
      - 48181:8181
```

      

This container works correctly. At the end of the day it's not a huge deal, but at least I'm up and running. Seem the container hosted here is hosed maybe?
