### ISSUE TITLE
Tautulli instances sporadically have their settings reset, exposing the admin interface to the public

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-tautulli#76]
**Describe the Bug**
My Tautulli instances will sporadically - and for seemingly no reason - have their settings reset after being restarted, such that the admin interface becomes publicly available for everyone who previously only had guest access until such time that I set a password in the settings again.

**Steps to Reproduce**
I have no way of reproducing the issue. I run five dockerized Tautulli instances on my server and it has happened about three times with each of them over the past month.

**Expected Behavior**
I expect Tautulli to retain its settings across restarts, unexpected crashes or whatever else may happen during regular or irregular operation.

**Tautulli and System Info**
- Version: 2.1.29
- Platform and Version: Debian Stretch
- Python Version: 2.7.16
- Browser and Version: Vivaldi v2.5.1525.40

**Link to logs**
https://gist.github.com/whalehub/faa8cb37760d2f78a8a4341eff7192ab

**Docker Compose file**
```yaml
version: '3.7'

services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/storage/docker/tautulli:/config
      - /mnt/storage/docker/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    networks:
      proxy:
        ipv4_address: 172.30.0.55
    env_file: /root/docker-compose/env/linuxserver.env

networks:
  proxy:
    external:
      name: proxy
```
